FROM jenkins/jenkins
 
USER root

RUN apt-get update -y
RUN apt-get install ca-certificates curl gnupg
RUN install -m 0755 -d /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN chmod a+r /etc/apt/keyrings/docker.gpg
RUN echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update

RUN apt-get -y install docker-ce

RUN apt-get -y install openssh-server

RUN useradd -ms /bin/bash remote_user && \
    echo "remote_user:homeeats" | chpasswd

USER root
RUN ls /home/remote_user
RUN mkdir "/home/remote_user/.ssh"
RUN chmod 777 "/home/remote_user/.ssh"

COPY worker_node.pub /home/remote_user/.ssh/authorized_keys

RUN chown remote_user:remote_user -R /home/remote_user/.ssh && \
    chmod 777 /home/remote_user/.ssh/authorized_keys

RUN ssh-keygen -A

RUN mkdir /var/run/sshd

CMD /usr/sbin/sshd -D
