name: Shell Commands

on:
  workflow_dispatch:

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"

      - name: List files before using actions/checkout
        run: |
          pwd
          ls

      - name: Run the actions/checkout
        uses: actions/checkout@v1
          
      - name: List files after using actions/checkout
        run: |
          pwd
          ls
  Check-environment-variables:
     runs-on: ubuntu-latest
     steps:
       - name: testing first variable
         run: |
           echo "first variable is the name of the runner OS $RUNNER_OS"
           echo "second variable is $GITHUB_REPOSITORY_OWNER"

  build:
     runs-on: self-hosted
     steps:
      - name: Run the actions/checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
